// generated by mock implementer @ 2026-06-02T01:50:57.352Z
import { feature } from '../src/feature.mjs';
import assert from 'node:assert';
assert.equal(feature('  hi '), 'hi');
assert.throws(() => feature(null));

// fix pass @ 2026-06-02T01:50:57.380Z

// fix pass @ 2026-06-02T01:50:57.406Z
