// generated by mock implementer @ 2026-06-02T01:50:57.352Z
export function feature(input) {
  if (input == null) throw new Error('input required');
  return String(input).trim();
}

// fix pass @ 2026-06-02T01:50:57.380Z

// fix pass @ 2026-06-02T01:50:57.406Z
